DaChuang/WebServer/dachuang/dachuang/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dcweb.urls')),

    # url(r'^', include('django.contrib.auth.urls'))
]

DaChuang/WebServer/dachuang/dcweb/urls.py
from django.conf.urls import url
from dcweb import views
from dcweb import android_views
from dcweb import data_views
from django.conf import settings
from django.conf.urls.static import static
from dcweb.views import test

urlpatterns = [
    url(r'^test$', test, name='test'),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^rec$', views.IndexRecView.as_view(), name='index_rec'),
    url(r'^star$', views.IndexStarView.as_view(), name='index_star'),

    url(r'^category/(?P<cate_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),

    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),

    url(r'^pub_list$', views.PublishView.as_view(), name='pub_list'),
    url(r'^pub_detail/(?P<pub_id>\d+)$', views.PubDetailView.as_view(), name='pub_detail'),

    url(r'^data$', data_views.data,name='data'),

    url(r'^person$', views.PersonView, name='person'),
    url(r'^person_edit$',views.update_data, name='person_edit'),

    url(r'^logout', views.do_logout, name='logout'),
    url(r'^reg', views.do_reg, name='reg'),
    url(r'^login', views.do_login, name='login'),

    url(r'^article/love$',views.love, name='love'),
    url(r'^article/loveoff/$',views.loveoff, name='loveoff'),
    url(r'^pub_detail/staring',views.staring, name='staring'),
    url(r'^pub_detail/staroff',views.staroff,name='staroff'),

    url(r'^gallery$',views.GalleryView.as_view(),name='gallery'),
    # ----------------------------------this is a part line-------------------------- #
    url(r'^app$', android_views.IndexView.as_view(), name='app_index'),
    url(r'^app_rec$', android_views.IndexRecView.as_view(), name='app_index_rec'),
    url(r'^app_star$', android_views.IndexStarView.as_view(), name='app_index_star'),

    url(r'^app_category/(?P<cate_id>\d+)$', android_views.CategoryView.as_view(), name='app_category'),
    url(r'^app_tag/(?P<tag_id>\d+)$', android_views.TagView.as_view(), name='app_tag'),

    url(r'^app_article/(?P<article_id>\d+)$', android_views.ArticleDetailView.as_view(), name='app_detail'),

    url(r'^app_pub_list$', android_views.PublishView.as_view(), name='app_pub_list'),
    url(r'^app_pub_detail/(?P<pub_id>\d+)$', android_views.PubDetailView.as_view(), name='app_pub_detail'),

    url(r'^app_data$', data_views.app_data,name='app_data'),

    url(r'^app_person$', android_views.PersonView, name='app_person'),
    url(r'^app_person_edit$', android_views.update_data, name='app_person_edit'),

    url(r'^app_logout', android_views.do_logout, name='app_logout'),
    url(r'^app_reg', android_views.do_reg, name='app_reg'),
    url(r'^app_login', android_views.do_login, name='app_login'),

    url(r'^app_article/love$', android_views.love, name='app_love'),
    url(r'^app_pub_detail/staring', android_views.staring, name='app_staring'),
    url(r'^app_pub_detail/staroff', android_views.staroff,name='app_staroff'),

    # url(r'^pub_detail/(?P<pub_id>\d+)$',views.PublishDetailView.as_View(),name='pub_detail'),
    # url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$', views.ArchiveView.as_view(), name='archive'),
    # url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentPostView.as_view(), name='comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DaChuang/WebServer/dachuang/dcweb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
# Create your models here.
# 我觉得这一部分可以将对数据库表和对数据库表的操作封装到一个类当中。

#tag 标签是从文章中通过智能分析获得的参数，标签是不定的。而不是一开始由用户给定的参数
class Tag(models.Model):
    name = models.CharField(max_length=30,verbose_name=u'标签名称')
    number = models.IntegerField(default=0,verbose_name=u'访问量')
    class Meta:
        verbose_name = u'标签'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


#class 表示文章不同的分类，是将文章归类到固定的栏目下边，类别试给定的。
class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name=u'分类名称')
    number = models.IntegerField(default=0,verbose_name=u'访问量')
    class Meta:
        verbose_name = u'分类'
        verbose_name_plural = verbose_name
        ordering = ['number', 'id']

    def __unicode__(self):
        return self.name



# source主要是publisher的类别，不固定。西工大微信，西工大官网，***学院新闻网
class Source(models.Model):
    name = models.CharField(max_length=300,verbose_name=u'来源类别')
    class Meta:
        verbose_name = u'发布者类别'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


# publisher信息的发布者，主要是微信公众号主体，各学院账号名称等。
class Publisher(models.Model):
    name = models.CharField(max_length=300,verbose_name=u'发布者名称')
    wechat_id = models.CharField(max_length=300,verbose_name=u'微信号',default='nothing' )
    img = models.ImageField(upload_to='pub',verbose_name=u'图片路径',blank=True,null=True)
    source = models.ForeignKey(Source,verbose_name=u'分类')
    intro = models.TextField(verbose_name=u'简介')
    class Meta:
        verbose_name = u'发布者'
        verbose_name_plural = verbose_name

    @property
    def img_url(self):
        if self.img and hasattr(self.img, 'url'):
            return self.img.url

    def __unicode__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name=u'文章标题')
    desc = models.CharField(max_length=300, verbose_name=u'文章描述', blank=True)
    content = models.TextField(verbose_name=u'文章内容')
    img = models.ImageField(upload_to='art', verbose_name=u'图片路径', blank=True, null=True)

    love_count = models.IntegerField(default=0, verbose_name=u'喜欢数')
    click_count = models.IntegerField(default=0, verbose_name=u'点击次数')

    date_publish = models.DateTimeField(auto_now_add=True, verbose_name=u'发布时间')
    tag_mark = models.BooleanField(verbose_name=u'标签标记',default=False,)

    publisher = models.ForeignKey(Publisher, verbose_name=u'发布者')
    category = models.ForeignKey(Category, blank=True, null=True, verbose_name=u'分类')
    tag = models.ManyToManyField(Tag, verbose_name=u'标签',blank=True)
    class Meta:
        verbose_name = u'文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    @property
    def img_url(self):
        if self.img and hasattr(self.img, 'url'):
            print self.img.url
            return self.img.url

    def increase_views(self):
        self.click_count += 1
        self.save(update_fields=['click_count'])

    def increase_loves(self):
        self.love_count += 1
        self.save(update_fields=['love_count'])

    def __unicode__(self):
        return self.title



# 每一个UserNormal中包含一个User对象，每一个User对象可以通过get_profile()方法，
# 返回与该对象相关的额外信息
class UserNormal(models.Model):
    STATUS_SIZE = (
        (0, u'男'),
        (1, u'女'),
    )
    user = models.OneToOneField(User)

    sex = models.IntegerField(default=0,blank=True,verbose_name='性别',choices=STATUS_SIZE)
    age = models.IntegerField(default=18,blank=True,verbose_name=u'年龄')

    phone = models.CharField(blank=True, max_length=20, verbose_name=u'电话',default='11011011011')

    desc = models.CharField(max_length=300,verbose_name=u'简介',default=u'小白')
    img = models.ImageField(upload_to='user', verbose_name=u'头像',null=True,default='1.jpg')

    @property
    def img_url(self):
        if self.img and hasattr(self.img, 'url'):
            return self.img.url

    def __unicode__(self):
        return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserNormal.objects.create(user=instance,img='1.jpg',desc=u'小白',phone='11011011011')

post_save.connect(create_user_profile, sender=User)

class History(models.Model):
    user = models.ForeignKey(User)
    article = models.ForeignKey(Article)
    time = models.DateTimeField(verbose_name='时间',auto_now=True)
    class Meta:
        verbose_name = u'历史记录'
        verbose_name_plural = u"浏览历史"

    def add(self,user,article):
        # print not History.objects.filter(user=user,article=article).exists()
        if not History.objects.filter(user=user,article=article).exists():
            print 'what fuck'
            Article.objects.filter(pk=article.pk).update(click_count=article.click_count + 1)

        History.objects.filter(user=user,article=article).delete()
        result = History(user=user,article=article)
        result.save()
        # article_item = Article.objects.get(pk=article)

        # history_list = History.objects.filter(user=user).order_by('time')
        # if len(history_list) > 10:
        #     history_list[0].delete()

    def __unicode__(self):
        return unicode(self.id)

class Love(models.Model):
    user = models.ForeignKey(User)
    article = models.ForeignKey(Article)
    time = models.DateTimeField(verbose_name='时间',auto_now=True)
    class Meta:
        verbose_name = u'喜欢记录'
        verbose_name_plural = u"喜欢"

    def add(self,user,article):
        if not Love.objects.filter(user=user,article=article).exists():
            Article.objects.filter(pk=article.pk).update(love_count=article.love_count + 1)
        Love.objects.filter(user=user,article=article).delete()
        result = Love(user=user,article=article)
        result.save()
        print "love successful"
        # article_item = Article.objects.get(pk=article)

    def dec(self,user,article):
        if Love.objects.filter(user=user,article=article).exists():
            Article.objects.filter(pk=article.pk).update(love_count=article.love_count -1)
        Love.objects.filter(user=user,article=article).delete()
        print 'love off successful'
        # result = Love(user=user,article=article)
        # result.save()
        # article_item = Article.objects.get(pk=article)

    def __unicode__(self):
        return unicode(self.id)


class Recommend(models.Model):
    user = models.ForeignKey(User)
    article = models.ForeignKey(Article)

    class Meta:
        verbose_name = u'推荐'
        verbose_name_plural = u"推荐"

    def __unicode__(self):
        return unicode(self.id)


class Star(models.Model):
    user = models.ForeignKey(User)
    publisher = models.ForeignKey(Publisher)

    class Meta:
        verbose_name = u'关注'
        verbose_name_plural = u"关注"

    def __unicode__(self):
        return unicode(self.id)

DaChuang/WebServer/dachuang/dcweb/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.conf import settings
from django.db.models import Q
from models import User
import re
from models import UserNormal
# 通过django定义的表单，统一前端和后台数据表达的方式，可以一次性完成验证数据、装载数据等操作
class LoginForm(forms.Form):
    '''
    登录Form
    '''
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username", "required": "required","class":"form-control",}),
                              max_length=50,error_messages={"required": "username不能为空",})
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password", "required": "required","class":"form-control",}),
                              max_length=20,error_messages={"required": "password不能为空",})

class RegForm(forms.Form):
    '''
    注册表单
    '''
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username", "required": "required","class":"form-control",}),
                              max_length=50,error_messages={"required": "username不能为空",})
    email = forms.EmailField(widget=forms.TextInput(attrs={"placeholder": "Email", "required": "required","class":"form-control",}),
                              max_length=50,error_messages={"required": "email不能为空",})
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password", "required": "required","class":"form-control",}),
                              max_length=20,min_length=6,error_messages={"required": "password不能为空",})


class PersonForm(forms.Form):
    '''
    评论表单
    '''
    sex = forms.IntegerField(widget=forms.TextInput(attrs={"placeholder": u"性别","id": "sex", "required": "required","tabindex": "1","class":"form-control",}),
                              error_messages={"required":"sex不能为空",},
                          label=u'性别',required=False)
    age = forms.IntegerField(widget=forms.TextInput(attrs={"placeholder": u"年龄","id":"age",
                                                           "required":"required", "tabindex":"2","class":"form-control",}),
                                 error_messages={"required":"age不能为空",},
                           label=u'年龄',required=False)
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder": u"电话","id":"phone","tabindex":"3","class":"form-control",}),
                              max_length=100, required=False,label=u'电话')
    desc = forms.CharField(widget=forms.Textarea(attrs={"placeholder": u"签名","id":"desc","required": "required", "cols": "80",
                                                           "rows": "5", "tabindex": "4","class":"form-control",}),
                                                    error_messages={"required":"评论不能为空",},
                           label=u'签名',required=False)
    img = forms.ImageField(label=u'头像', required=True)

class PersonsForm(forms.ModelForm):
    class Meta:
        model = UserNormal
        fields = [ 'age','sex','phone','desc','img']
        widgets = {
            'sex':forms.Select(attrs={"placeholder": u"性别","id": "sex", "required": "required","tabindex": "1","class":"form-control",}),
            'age':forms.NumberInput(attrs={"placeholder": u"年龄","id":"age", "required":"required", "tabindex":"2","class":"form-control",}),
            'phone':forms.TextInput(attrs={"placeholder": u"电话","id":"phone","tabindex":"3","class":"form-control",}),
            'desc':forms.Textarea(attrs={"placeholder": u"签名","id":"desc","required": "required", "cols": "80", "rows": "5", "tabindex": "4","class":"form-control",}),
        }

DaChuang/WebServer/dachuang/dcweb/templates/blog/comment.html
<div class="comment">
    <div class="comment-main">
        <p class="head">评论详情</p>
        <form method="post" action="{% url 'blog:comment' article.pk %}">
            {% csrf_token %}
            <div class="row">
                {% for field in form %} {{ field }} {{ field.errors }}
                <br> {% endfor %}
            </div>
            <button type="submit" class="com-button">评论</button>
        </form>
        <p class="comment-count">共{{ 0 }}条评论</p>
        <hr> {% for comment in comment_list %}
        <div class="main-content">
            {# <img src="月英1.jpg" class="user-avatar">#}
            <span class="user-nickname">{{ comment.user_name }}</span>
            <time class="time">{{ comment.created_time }}</time>
            <div class="comment-content">
                {{ comment.body }}
            </div>
            {#<a href="">回复</a>#}
        </div>
        <hr> {% endfor %}
    </div>
</div>

DaChuang/WebServer/dachuang/dcweb/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div id="bd" class="wrp clear-fix">
            <div id="main">
                <!--位置栏 start-->
                <div id="detail-title">
                    <ul id="single-nav">
                        <li><a href="{% url 'index' %}">首页</a></li>
                        <li>&gt;</li>
                        <li>
                            <ul class="post-categories">
                                <li><a href="" title="" rel="category">{{ article.category }}</a>
                                </li>
                            </ul>
                        </li>
                        <li>&gt;</li>
                        <li class="title-active"><a href="{% url 'detail' article.pk %}" rel="bookmark">{{ article.title }}</a>
                        </li>
                    </ul>
                </div>
                <!--位置栏 end-->
                <div id="post-1951" class="post-1951 post type-post status-publish format-standard hentry category-meida-report">
                    <div class="post-hd">
                        <h1 class="title text-center">{{ article.title }}</h1>
                    </div>
                    <hr/>
                    <!--副标题 start-->
                    <div class="date-read">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
                                <span class="center-block">
                                    <i class="icon-date text-center"></i><span class="date">{{ article.date_publish|date:"Y年n月d日" }}</span>
                                </span>
                            </div>
                            <div class="col-lg-6 col-md-6col-sm-6 col-xs-6  text-center" >
                                <div class="wrap ">
                                    <a href="{% url 'pub_detail' article.publisher.pk %}" class="more text-center"><span class="glyphicon glyphicon-user" aria-hidden="true">{{ article.publisher }}</span></a>
                                </div>
                            </div>
                            <br/>
                        </div>
                        <!-- tags -->
                        <div class="btn-group btn-group-justified" role="group">
                            {% for tag in tag_list %}
                            <a href="{% url 'tag' tag.pk %}" class="btn btn-default">{{ tag.name }} </a>
                            {% endfor %}
                        </div>
                        <br/>
                        <br/>
                        <!--picture start -->
                        <img src="{{article.img_url}}" alt="hello world" onerror="this.src='{{article.publisher.img_url|default_if_none:'#'}}'" class="img-responsive center-block img-rounded">
                        <!--picture end-->
                        <br/>
                    </div>
                    <!--副标题 end-->
                    <!--内容 start-->
                    <div class="post-bd">
                        <div class="text-justify line-intent">
                            {{ article.content |linebreaks }}
                        </div>
                    </div>
                    <!--内容 end-->
                    <!--辅助栏 start-->
                    <div class="post-ft">
                        <div class="row">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center">
                                <span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center" >
                                <span class="glyphicon glyphicon-eye-open" style="color:blue;" aria-hidden="true">&nbsp;{{ article.click_count}}</span>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-center">
                                {% if love %}
                                <a href="loveoff/?article_id={{article.id}}"><span class="glyphicon glyphicon-heart" style="color:red;" aria-hidden="true">&nbsp;{{ article.love_count }}</span></a>
                                {% else %}
                                <a href="love/?article_id={{article.id}}"> <span class="glyphicon glyphicon-heart" style="color:#505050;" aria-hidden="true">&nbsp;{{ article.love_count }}</span></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <!--辅助栏 end-->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

DaChuang/WebServer/dachuang/dcweb/templates/blog/pagination.html
<div id="pagenavi" class="noselect">
    {% if article_list.has_previous %}
        <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    {% if first_page == current_page %}
        <span class="first-page current">1</span>
    {% else %}
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %}
        <span>...</span>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <span class="current">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    {% if article_list.has_next %}
        <a class="next-page" href="?page={{ article_list.next_page_number }}">
            下一页<span class="icon-next"></span>
        </a>
    {% endif %}
</div>

DaChuang/WebServer/dachuang/dcweb/templates/blog/person.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | ChartJS</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'adminlte/bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">

  <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/pygments/github.css' %}">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
{% endblock %}

{% block content %}
<div class="container">
<div class="wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- The time line -->
          <ul class="timeline">
            <!-- timeline time label -->
            <li class="time-label">
                  <span class="bg-aqua">
                    <img class="profile-user-img img-responsive img-circle" src="{{ user_normal.img.url }}" alt="User profile picture">
                  </span>
            </li>
            <!-- /.timeline-label -->
              <!-- timeline item -->
            <li>
              <i class="fa fa-user bg-aqua"></i>

              <div class="timeline-item">
                <span class="time"></span>

                <h3 class="timeline-header no-border"><a href="#">{{ request.user.username}}</a></h3>
                <div class="timeline-body">
                    <h4><span class="time"><i class="fa fa-envelope-o"></i>邮箱：</span><em>{{ request.user.email}}</em></h4>
                </div>
                <div class="timeline-footer">
                </div>
              </div>

            </li>
            <!-- END timeline item -->
            <!-- timeline item -->
            <li>
              <i class="fa fa-envelope bg-blue"></i>

              <div class="timeline-item">
                <span class="time"></i></span>

                <h3 class="timeline-header"><a href="#">基本信息</a></h3>

                <div class="timeline-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <h4><span class="time"><i class="fa fa-phone"></i>电话：</span>{{ user_normal.phone }}</h4>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <h4><span class="time"><i class="fa fa-intersex"></i>性别：</span>{{ user_normal.get_sex_display }}</h4>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <h4><span class="time"><i class="fa fa-hourglass-2"></i>年龄：</span>{{ user_normal.age }}<br/></h4>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="timeline-footer">
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'person_edit' %}" class="btn btn-primary btn-xs">修改个人信息</a>
                </div>
              </div>
            </li>
            <!-- END timeline item -->

            <!-- timeline item -->
            <li>
              <i class="fa fa-comments bg-yellow"></i>

              <div class="timeline-item">
                <span class="time"></i> </span>

                <h3 class="timeline-header"><a href="#">个性签名</a></h3>

                <div class="timeline-body" style="text-intent:2em;">
                    <h5>{{ user_normal.desc }}</h5>
                </div>

              </div>
            </li>
            <!-- END timeline item -->
            <!-- timeline time label -->
            <li class="time-label">
                  <span class="bg-green">
                    关注的人
                  </span>
            </li>
            <!-- /.timeline-label -->
            <!-- timeline item -->
            <li>
              <i class="fa fa-camera bg-purple"></i>

              <div class="timeline-item">
                <span class="time"></i></span>

                <h3 class="timeline-header"><a href="#">关注的发布者</a></h3>

                <div class="timeline-body">
                        <div class="row">
                            {% for pub in pub_list %}
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <div class="panel panel-default">
                                      <div class="panel-body">
                                          <img src="{{pub.img.url}}" class="img-responsive center-block">
                                      </div>
                                      <div class="panel-footer">
                                          <a href="{% url 'pub_detail' pub.pk %}" class="more text-center"><p class="text-center"> {{ pub.name }} </p></a>
                                      </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>

                </div>
              </div>
            </li>
            <!-- END timeline item -->
              <!-- timeline time label -->
            <li class="time-label">
                  <span class="bg-green">
                    历史记录
                  </span>
            </li>
            <!-- /.timeline-label -->

            <!-- timeline item -->
              {% for article in history_list %}
            <li>
              <i class="fa fa-clock-o {% cycle 'bg-maroon' 'bg-yellow' 'bg-blue' 'bg-green' 'bg-purple' %}"></i>
              <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i>{{ article.1|date:"Y年n月d日h:i:s" }}</span>

                <h3 class="timeline-header"><a href="{% url 'detail' article.0.pk %}">{{ article.0.title }}</a></h3>

                <div class="timeline-body">
                    {{ article.0.desc }}
                </div>
                <div class="timeline-footer">
                    <span class="date">{{ article.0.date_publish|date:"Y年n月d日" }}</span>&nbsp;&nbsp;
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true">{{ article.0.category }}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <span class="glyphicon glyphicon-user" aria-hidden="true">{{ article.0.publisher }}</span>
                </div>
              </div>
            </li>
              {% endfor %}
              <!--结尾的标志-->
            <li>
              <i class="fa fa-hand-pointer-o bg-gray"></i>
            </li>
          </ul>
        </div>
        <!-- /.col -->
      </div>
    </section>
</div>
</div>

{% endblock  %}
{% block js %}
<!-- jQuery 2.2.3 -->
<script src="{% static 'adminlte/plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'adminlte/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- ChartJS 1.0.1 -->
<script src="{% static 'adminlte/plugins/chartjs/Chart.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'adminlte/plugins/fastclick/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/dist/js/app.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'adminlte/dist/js/demo.js' %}"></script>
<!-- page script -->
<script src="{% static 'adminlte/data.js' %}"></script>

{% endblock %}